name : Build Status


on : 
  pull_request:
    branches : 
      - main

jobs:
    Continuous-Integration:
        name : Perform Build
        runs-on: ubuntu-latest
        steps:
          - name : Checkout Repository
            uses: actions/checkout@v3
          
          - name : SetUp Nodejs
            uses: actions/setup-node@v2
            with:
              node-version: '20'
          - name : Install Dependencies
            run : npm install --legacy-peer-deps

          - name : Generate Prisma client
            run : npm run db:generate

          - name : Builds the Project
            run  : npm run build




# name: Build on PR

# on:
#   pull_request:
#     branches:
#       - main

# jobs:
#   build:
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v3
#       - name: Use Node.js
#         uses: actions/setup-node@v3
#         with:
#           node-version: '20'
      
#       - name: Install Dependencies
#         run: npm install
        
#       - name: Run Build
#         run: npm run build
